### ISSUE TITLE
add real test jobs to jenkins docker image

### ISSUE THREAD

**Issue by EugenWiens** [EugenWiens/jenkins-head#14]
@leinher what do you mean?
I will create following jobs:

1. TestJob1-FS:
Free Style job that always success

2. TestJob2-FS:
Free Style job that has a checkbox (checked => fail, not checked => success)

3. TestJob3-PL:
Pipe-Line Job where the Pipe-Line is configured in the job itself and this job always success

4. TestJob4-PL:
Pipe-Line Job where the Pipe-Line is configured in the job itself and this job has a checkbox (checked => fail, not checked => success)

**Comment by leinher** [comment]
We also need a multi branch pipeline to check if a pipeline/branch can be tracked

**Comment by EugenWiens** [comment]
5. TestJob5-MBPL:
Multi-Branch Pipe-Line Job where the Pipe-Line is configured in a file including in this project and this job has a checkbox (checked => fail, not checked => success)

**Comment by EugenWiens** [comment]
- [ ] TestJob1-FS: Free Style job that always success
- [ ] TestJob2-FS: Free Style job that has a checkbox (checked => fail, not checked => success)
- [ ] TestJob3-PL: Pipe-Line Job where the Pipe-Line is configured in the job itself and this job always success
- [ ] TestJob4-PL: Pipe-Line Job where the Pipe-Line is configured in the job itself and this job has a checkbox (checked => fail, not checked => success)
- [ ] TestJob5-MBPL: Multi-Branch Pipe-Line Job where the Pipe-Line is configured in a file including in this project and this job has a checkbox (checked => fail, not checked => success)
