### ISSUE TITLE
create a docker instance to test the jenkins api handler

### ISSUE THREAD

**Issue by EugenWiens** [EugenWiens/jenkins-head#8]

**Comment by leinher** [comment]
![image](https://user-images.githubusercontent.com/53341108/79083271-8f560100-7d2d-11ea-9975-0bc02e14e623.png)

jenkins is up and running. See instructions at #10 
@EugenWiens we could copy a container snapshot to save the installation. Interested?

**Comment by EugenWiens** [comment]
This is ok for the start. I will create docker image for integration tests not for the API. See #12

**Comment by EugenWiens** [comment]
see #13
