### ISSUE TITLE
pytest hierarchy for the BLE-GATT-Client Project

### ISSUE THREAD

**Issue by EugenWiens** [EugenWiens/jenkins-head#9]
The BLE-GATT-Client is a python3-only project because of that, it is better to do an overall unit test. This issue should be a discussion to find the best folder hierarchy.
@leinher what's your opinion to the following hierarchy

![image](https://user-images.githubusercontent.com/7880602/78505250-9059c200-7772-11ea-8e16-8dc5e706c599.png)

**Comment by leinher** [comment]
In this project the name GATT client is ok. Nevertheless the python package we are going to create should have a different name.
First idea: `jenkins-head-control`: A user will install an use it for the jenkins heads not as a generic GATT-Client.

I think we should separate the python package and *other things*.

![image](https://user-images.githubusercontent.com/53341108/78508387-d3259500-7786-11ea-934a-25fa23e378ab.png)

**Comment by leinher** [comment]
Pushed this suggestion for further improvements. see [here](https://github.com/EugenWiens/jenkins-head/tree/folderStructureGattClient)

**Comment by EugenWiens** [comment]
Your right. I didn't think about the focus of the python part. Let's set a few key requirements.

**Comment by EugenWiens** [comment]
1. all classes are tested with unittest. The threshold of the code coverage is defined later

**Comment by EugenWiens** [comment]
2. This python daemon is written in python3

**Comment by EugenWiens** [comment]
3. This python daemon is published via pip as a package

**Comment by EugenWiens** [comment]
4. The name `jenkins-head-control` suggests that the python daemon can use to control the head. My suggestion is `jenkins-head-controller`.

**Comment by EugenWiens** [comment]
5. Did we use an python virtual environment for the development? I would say yes.

**Comment by EugenWiens** [comment]
6. folder hierarchy for the BLE-GATT-Client

> I think we should separate the python package and _other things_.
> 
> ![image](https://user-images.githubusercontent.com/53341108/78508387-d3259500-7786-11ea-934a-25fa23e378ab.png)

**Comment by leinher** [comment]
>     1. Did we use an python virtual environment for the development? I would say yes.
We have to! This is the only way to get rid of 'It works on my machine'

**Comment by EugenWiens** [comment]
commitments:
1. to increase the quality we will use **unit-tests** during the development
2. we will only use **python3**
3. the service will be published via **pip**
4. the name of the process and service is `jenkins-head-controller`
5. for development we use **virtual env**
6. we will separate the python source code from **other things** see:
> 1. folder hierarchy for the BLE-GATT-Client
> 
> > I think we should separate the python package and _other things_.
> > ![image](https://user-images.githubusercontent.com/53341108/78508387-d3259500-7786-11ea-934a-25fa23e378ab.png)
